setting:
    sandbox         : true
    security_plugin : 1
    request_log     : false
    sql_log         : false
    timezone        : UTC
    cache_time      : 600
    secret_key      : xxxxxxxxxxxxxxxx
    app_id          : top

db_data:
    adapter     : Mysql
    host        : 127.0.0.1
    username    : root
    password    : root
    dbname      : v3-top
    charset     : utf8mb4
    port        : 3306

db_backend:
    adapter     : Mysql
    host        : 127.0.0.1
    username    : root
    password    : root
    dbname      : v3-top
    charset     : utf8mb4
    port        : 3306

redis:
    host        : 127.0.0.1
    port        : 6379
    index       : 1
    prefix      : cache_

mq:
    host        :
    port        :
    username    :
    password    :
    vhost       :

sso:
    base_url    : http://v3-top.com/api/sso/
    sessionlog_url11 : https://top.local.com/api/sessionlog